eureka:
  instance:
    hostname: gateway-microservice
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://discovery-microservice:8001/eureka/
    registryFetchIntervalSeconds: 1

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  prefix: /api
  routes:
    product-catalog-microservice:
      path: /products-service/**
      #stripPrefix: false
      service-id: product-catalog-microservice
      #url: http://product-catalog-microservice:9001
    cart-microservice:
      path: /cart-service/**
      #stripPrefix: false
      service-id: CART-MICROSERVICE
    cart-client-microservice: 
      path: /cart-client-service/**
      #stripPrefix: false
      service-id: CART-CLIENT-MICROSERVICE