server:
  port: 8000

zuul:
  prefix: /api
  routes:
    product-catalog-microservice:
      path: /products-service/**
      #stripPrefix: false
      service-id: product-catalog-microservice
      #url: http://product-catalog-microservice:9001

    cart-microservice:
      path: /cart-service/**
      #stripPrefix: false
      service-id: CART-MICROSERVICE

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

product-catalog-microservice:
  ribbon:
    readTimeout: 20000
microservice:
  ribbon:
    readTimeout: 20000