FROM smebberson/alpine-redis

#MAINTAINER Venkata Ravuri <venkat@nikhu.com>

RUN apk add --update curl && \
    rm -rf /var/cache/apk/*

COPY redis-local.conf /etc/redis-local.conf

EXPOSE 6379

CMD [ "redis-server", "--protected-mode", "no" ]

#docker build . -t ecommerce/redis
#docker run --rm --name redis  ecommerce/redis
#docker exec -it redis redis-cli


